PRODUCTS_CONFIG = [
    {
        "id": "etprime",
        "name": "ET Prime",
        "priority": 1,
        "category": "premium_analysis",
        "intents": ["news", "investing", "growing_business"],
        "sophistication": ["intermediate", "expert"],
        "goals": ["wealth_building", "protecting_wealth"],
        "professions": ["corporate_professional", "senior_executive", "founder", "hni"],
        "interests": ["markets", "startups", "macro_economy", "corporate_strategy"]
    },
    {
        "id": "etmarkets",
        "name": "ET Markets",
        "priority": 1,
        "category": "active_trading",
        "intents": ["investing", "news"],
        "sophistication": ["intermediate", "expert"],
        "goals": ["wealth_building"],
        "professions": ["active_trader", "retail_investor", "hni"],
        "interests": ["markets", "stock_trading", "ipo", "technical_analysis"]
    },
    {
        "id": "etmoney",
        "name": "ET Money",
        "priority": 2,
        "category": "wealth_management",
        "intents": ["investing"],
        "sophistication": ["beginner", "intermediate"],
        "goals": ["wealth_building", "saving_specific", "tax_saving"],
        "professions": ["salaried_employee", "retail_investor", "mutual_fund_investor"],
        "interests": ["personal_finance", "mutual_funds", "tax_planning"]
    },
    {
        "id": "etrise",
        "name": "ET Rise",
        "priority": 3,
        "category": "sme_growth",
        "intents": ["growing_business"],
        "sophistication": ["beginner", "intermediate", "expert"],
        "goals": ["business_scaling", "funding"],
        "professions": ["sme_owner", "startup_founder", "entrepreneur"],
        "interests": ["startups", "msme_policy", "business_finance"]
    },
    {
        "id": "etmasterclass",
        "name": "ET Masterclass",
        "priority": 3,
        "category": "upskilling",
        "intents": ["growing_business", "news"],
        "sophistication": ["beginner", "intermediate"],
        "goals": ["career_growth", "wealth_building"],
        "professions": ["student", "young_professional", "salaried_employee", "senior_executive"],
        "interests": ["ai", "leadership", "wealth_mastery", "future_skills"]
    },
    {
        "id": "etbrandequity",
        "name": "ET BrandEquity",
        "priority": 3,
        "category": "marketing_intelligence",
        "intents": ["news", "growing_business"],
        "sophistication": ["intermediate", "expert"],
        "goals": ["professional_authority"],
        "professions": ["corporate_professional", "senior_executive", "marketing_head"],
        "interests": ["advertising", "marketing", "martech", "consumer_behavior"]
    },
    {
        "id": "etgovernment",
        "name": "ET Government",
        "priority": 4,
        "category": "governance_intelligence",
        "personas": ["senior_executive", "corporate_professional", "nri"],
        "intents": ["news", "growing_business"],
        "sophistication": ["intermediate", "expert"],
        "goals": ["career_growth", "professional_authority"],
        "professions": ["senior_executive", "corporate_professional", "ias_ips_officer", "policy_maker"],
        "interests": ["e_governance", "policy_reform", "smart_infrastructure", "digital_india", "psu"]
    },
    {
        "id": "ettravelworld",
        "name": "ET TravelWorld",
        "priority": 4,
        "category": "travel_hospitality",
        "personas": ["corporate_professional", "senior_executive", "hni", "nri"],
        "intents": ["news", "growing_business"],
        "sophistication": ["beginner", "intermediate", "expert"],
        "goals": ["wealth_building", "career_growth"],
        "professions": ["corporate_professional", "travel_agent", "hospitality_manager", "airline_executive"],
        "interests": ["aviation", "hospitality", "tourism_policy", "wellness_tourism", "destination_analysis"]
    },
    {
        "id": "etevents",
        "name": "ET Events",
        "priority": 4,
        "category": "leadership_networking",
        "personas": ["senior_executive", "startup_founder", "hni", "corporate_professional"],
        "intents": ["growing_business", "news"],
        "sophistication": ["intermediate", "expert"],
        "goals": ["professional_authority", "career_growth"],
        "professions": ["senior_executive", "founder", "corporate_professional", "cxo"],
        "interests": ["global_business_summit", "networking", "thought_leadership", "industry_awards", "geopolitics"]
    },
    {
        "id": "etnow",
        "name": "ET Now",
        "priority": 2,
        "category": "broadcast_intelligence",
        "intents": ["news", "investing"],
        "sophistication": ["beginner", "intermediate", "expert"],
        "goals": ["wealth_building", "protecting_wealth"],
        "professions": ["active_trader", "retail_investor", "corporate_professional", "senior_executive"],
        "interests": ["markets", "macro_economy", "ipo", "corporate_action", "forex"]
    },
]
